deploy:
  skip_cleanup: true

# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

#sudo: false
#language: cpp

# Define the matrix explicitly, manually expanding the combinations of (os, compiler, env).
# It is more tedious, but grants us far more flexibility.
#matrix:
#  include:
#      - os: linux
#        compiler: gcc
#        sudo : true

# These are the install and build (script) phases for the most common entries in the matrix.  They could be included
# in each entry in the matrix, but that is just repetitive.
#install:
#  - ./ci/install-${TRAVIS_OS_NAME}.sh
#  - . ./ci/env-${TRAVIS_OS_NAME}.sh
#  - ./ci/log-config.sh

notifications:
  email: false  
